[project]
name = "pet1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Danil Dolintsev", email = "danitizzer@gmail.com" }
]
requires-python = ">=3.10"
dependencies = []

[project.scripts]
pet1 = "pet1:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.8",
]
